### PR TITLE
use unittest2 instead of unittest

### PR DESCRIPTION
**Pull request by ehenneken**
The unit tests for sample_application2 use just 'unittest' which doesn't support 'discover'

### CODE REVIEW

**Comment by vsudilov** [comment]
What do you mean by doesn't support 'discover'? These changes require adding `unittest2` to `requirements.txt` (see the build failure); what are some advantages that justify adding that as a dependency?

**Comment by ehenneken** [comment]
I meant

  suite = unittest.TestLoader().discover('unittests')

will fail, but

  suite = unittest2.TestLoader().discover('unittests')

works, at least that was my experience.

**Comment by vsudilov** [comment]
Could this be related to your local python version? The tests (including the snippet you pasted above) pass on 2.7.

**Comment by ehenneken** [comment]
I thought we developed under 2.6 still. Python 2.7 is news to me :-)

**Comment by vsudilov** [comment]
Nope, there no need to support 2.6 AFAIK. Closing.

**Pull request closed without merging**
