### PR TITLE
Issue #17: example files to be used for the documentation of the blue…

### PR DESCRIPTION
**Pull request by jonnybazookatone**
…print, and the pattern for any future sample applications in terms of documentation.

Some of the files may be overkill for even existing (CHANGES and CONTRIBUTING), but it's worth talking about to be on the same page.

### CODE REVIEW

**Comment by vsudilov** [comment]
contributing and authors should be included; I'm not sold on changes. That file would require a lot of effort to keep up to date -- what are the benefits of putting in that effort?

**Comment by ehenneken** [comment]
I agree with @vsudilov; I don't think I'd be maintaining a CHANGES file.

**Comment by jonnybazookatone** [comment]
I can agree. I do think the overhead in keeping the CHANGES.md up to date, depends on how much detail you decide to put in to it.

One benefit I see can be related to rollbacks and version descriptions. For example, if we want to rollback to a certain state, yet we do not really understand what the release tags are referring to, and the commits do not really help, and the person is unavailable/does not remember the exact changes. Both the comments and semantic numbering can help a lot I think.

s

**Comment by vsudilov** [comment]
Agreed in principle, but let's just annotate release tags to achieve that. Could you remove the CHANGES.md, please? I'll merge after that.

**Pull request merged**
